### ISSUE TITLE
Project and package need to have same canonical name

### ISSUE THREAD

**Issue by cjolowicz** [cjolowicz/blog#6]
[Reported by Anders Lindstrom on Medium](https://medium.com/@anderslindstrom/hi-claudio-d39fe46edb2c):

There’s one small issue that I encountered. It’s to do with the `poetry install` stage. Because I had renamed my package `anders-hypermodern-python`, poetry was unable to find the source under the `src` directory. If I renamed the package from `src/hypermodern_python` to `src/anders_hypermodern_python` it picked it up automatically. Another solution was to add the following to the pyproject.toml:

```toml
[tool.poetry]
# …
packages = [
    { include = “hypermodern_python”, from = “src” },
]
```
